config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  # groups controller
  resources :groups

  # ads controller
  resources :ads do
    resources :comments
    resource :bookmark
  end

  # users could sign up multiple times
  resources :users do
    resources :testimonials
  end

  # users can only make one session
  resource :session

  resource :account

  get "about", to: "pages#about"
  
  root "pages#home"
end

app/models/ad.rb
class Ad < ApplicationRecord
  # add an association that has a 1-to-many relationship
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  # add an association to the user
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
  validates :category, presence: true

  def to_param
    id.to_s + '-' + title.parameterize
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :ad
  belongs_to :user

  validates :ad, uniqueness: { scope: :user }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :ad
  belongs_to :user

  validates :body, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users

  validates :name, presence: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/page.rb
class Page < ApplicationRecord
  validates :url, uniqueness: true

  mount_uploader :image, ContentImageUploader
end

app/models/testimonial.rb
class Testimonial < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :receiver, class_name: 'User'

  validates :body, presence: true
  validates :author_id, presence: true
  validates :receiver_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :ads, dependent: :destroy
  has_many :comments
  has_many :bookmarks, dependent: :destroy
  has_many :group_users
  has_many :groups, through: :group_users

  has_many :author_testimonials, class_name: 'Testimonial', foreign_key: 'author_id'
  has_many :receiver_testimonials, class_name: 'Testimonial', foreign_key: 'receiver_id'

  has_secure_password

  # add the photo uploader
  mount_uploader :photo, PhotoUploader

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true

  def to_param
    username
  end
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  def index
    @category = params[:category]

    @ads = if @category.present?
             # filter by category (request or offer)
             Ad.where(category: @category)
           else
             Ad.all
           end
  end

  def new
    @ad = Ad.new
  end

  def create
    @ad = Ad.new(form_params)

    # and then associate it with a user
    @ad.user = @current_user

    if @ad.save
      flash[:success] = 'Your ad was posted!'

      redirect_to root_path
    else
      # show the view for new.html.erb
      render 'new'
    end
  end

  def show
    @ad = Ad.find(params[:id])
  end

  def destroy
    @ad = Ad.find(params[:id])

    # destroy if they have access
    if @ad.user == @current_user
      @ad.destroy

      flash[:success] = 'Ad deleted successfully!'
    end

    # redirect to the home page
    redirect_to root_path
  end

  def edit
    @ad = Ad.find(params[:id])

    redirect_to root_path if @ad.user != @current_user
  end

  def update
    @ad = Ad.find(params[:id])

    if @ad.user != @current_user
      redirect_to root_path
    elsif @ad.update(form_params)
      flash[:success] = 'Ad updated successfully!'

      redirect_to ad_path(@ad)
    else
      render 'edit'
    end
  end

  def form_params
    params.require(:ad).permit(:title, :body, :category)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @content = Page.find_by(url: 'home')

    @latest_ads = Ad.where('created_at > ?', 1.week.ago).limit(3)

    @featured_ads = Ad.where(is_featured: true)
  end

  def about
    @content = Page.find_by(url: 'about')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @studio = params[:studio_number]

    @users = if @studio.present?
               # filter by studio
               User.where(studio_number: @studio)
             else
               User.all
             end
  end

  def show
    @user = User.find_by(username: params[:id])
  end

  def new
    # a form for adding a new user
    @user = User.new
  end

  def create
    # take the params from the form
    # create a new user
    @user = User.new(form_params)

    # if its valid and it saves, go to the list users page
    # if not, see the form with errors
    if @user.save
      # save the session with the user
      session[:user_id] = @user.id

      flash[:success] = "Welcome to Uliving Rio's Bulletin Board!"

      redirect_to users_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find_by(username: params[:id])

    redirect_to root_path if @user != @current_user
  end

  def update
    flash[:success] = 'Profile updated successfully!' if @current_user.update(profile_form_params)

    redirect_to user_path(@current_user)
  end

  def form_params
    params.require(:user).permit(:username, :email, :phone_number, :studio_number, :password, :password_confirmation)
  end

  def profile_form_params
    params.require(:user).permit(:real_name, :birthday_date, :phone_number, :description, :studio_number, :photo)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ads/_form.html.erb
<%= simple_form_for @ad do |f| %>

  <div class="ad-info">
    <%= f.input :category, label: "What you looking for?", :include_blank => "Choose a category", :as => :select,
      :collection =>  [["I wanna learn", :request], ["I can help/teach", :offer], ["Let's do something together", :exchange]] %>
    <%= f.input :title %>
    <%= f.input :body, label: "Your message" %>
  </div>

  <%= f.button :submit, "Save your ad" %>

<% end %>

app/views/ads/edit.html.erb
<h3>Edit your ad!</h3>

<%= render "form" %>

app/views/ads/index.html.erb
<% content_for :page_title, "Homepage" %>

<nav class="filters">
  <%= active_link_to "All Ads", ads_path, active: { category: nil } %>
  <%= active_link_to "Requests", ads_path(category: "request"), active: { category: "request" } %>
  <%= active_link_to "Offers", ads_path(category: "offer"), active: { category: "offer" } %>
  <%= active_link_to "Exchanges", ads_path(category: "exchange"), active: { category: "exchange" } %>
</nav>

<% @ads.each do |ad| %>

  <div class="ad-item">
    <%= link_to ad_path(ad) do %>
      <h2><%= ad.title %></h2>
      <p>
        <%= pluralize ad.comments.count, "comment" %>
      </p>
    <% end %>
  </div>

<% end %>

app/views/ads/new.html.erb
<% content_for :page_title, "Create a new ad" %>

<h3>Create a new ad</h3>

<%= render "form" %>

app/views/ads/show.html.erb
<% content_for :page_title, @ad.title %>

<h1 class="show-ad-title"><%= @ad.title %></h1>

<% if is_logged_in? %>

  <div class="bookmark">
    <% if @ad.bookmarks.where(user: @current_user).any? %>

      <%= link_to "unbookmark", ad_bookmark_path(@ad), method: :delete %>

    <% else %>

      <%= link_to "bookmark", ad_bookmark_path(@ad), method: :post %>

    <% end %>
  </p>


<% end %>

<div class="ad">
  <div class="user">
    Hi! I'm  
    <% if @ad.user.present? %>

      <%= link_to @ad.user.username, user_path(@ad.user) %>

    <% else %>
      anonymous
    <% end %>
  </div>

  <div class="studio">
    <% if @ad.user.studio_number.present? %>
      From studio <%= @ad.user.studio_number %>
    <% end %>
  </div>

  <div class="textarea">
    <%= simple_format @ad.body %>
  </div>

  <% if @ad.user.phone_number.present? %>
    <div class="phone_number">
      <a href="https://api.whatsapp.com/send?phone=<%= @ad.user.phone_number %>" target="_blank" rel="noopener noreferrer">Send Message Via Whatsapp</a>
    </div>
  <% end %>

  <% if @ad.bookmarks.any? %>
    <h3>Bookmarked by...</h3>
  <% end %>

  <ul>
    <% @ad.bookmarks.each do |bookmark| %>
      <li><%= bookmark.user.username %></li>
    <% end %>
  </ul>

  <div class="updated_at">
    Published on <%= @ad.updated_at.strftime("%d %B, %Y %I:%M%p") %>
  </div>

</div>

<% if @ad.user == @current_user %>
  <div class="actions">
    <%= link_to "Delete this ad", ad_path(@ad), method: :delete, data: { confirm: "Are you sure?" } %>
    <%= link_to "Edit this ad", edit_ad_path(@ad) %>
  </div>
<% end %>

<h3>Comments</h3>

<% @ad.comments.order("created_at desc").each do |comment| %>
  <div class="comment">
    <%= simple_format comment.body %>

    <p class="posted">
      Posted by
        <% if comment.user.present? %>

          <%= link_to comment.user.username, user_path(comment.user) %>

        <% else %>

          anonymous

        <% end %>

      <%= time_ago_in_words comment.created_at %> ago.
    </p>

  </div>
<% end %>

<h3>Add a comment</h3>

<%= simple_form_for [@ad, Comment.new] do |f| %>

  <%= f.input :body, label: "Your comment" %>
  <%= f.button :submit, "Add comment" %>

<% end %>

app/views/groups/index.html.erb
<% content_for :page_title, "Groups" %>

<h2>Groups</h2>

<% @groups.each do |group| %>

  <p><%= link_to group.name, group_path(group) %></p>

<% end %>

app/views/groups/show.html.erb
<% content_for :page_title, @group.name %>

<h2><%= @group.name %></h2>

<ul>
  <% if @group.users.any? %>

    <% @group.users.each do |user| %>
      <li><%= link_to user.username, user_path(user) %></li>
    <% end %>

  <% end %>
</ul>

<p><%= link_to "Back to all groups", groups_path %></p>

app/views/users/edit.html.erb
<% content_for :page_title, "Edit profile" %>

<h2>Edit profile</h2>

<%= simple_form_for @current_user, url: user_path do |f| %>
  <%= f.input :real_name, label: "Name" %>
  <%= f.input :studio_number, label: "Studio number" %>
  <%= f.input :birthday_date, start_year: 1950, label: "Birthday" %>
  <%= f.input :phone_number, label: "Whatsapp", placeholder: "e.g. 5521999999999", hint: ' Only digits, please.' %>
  <%= f.input :description, label: "Description" %>
  <%= f.input :photo, label: "Photo" %>

  <%= f.button :submit, "Update profile" %>
<% end %>

app/views/users/index.html.erb
<% content_for :page_title, "All users" %>

<nav class="filters">
  <%= active_link_to "All users", users_path, active: { studio_number: nil } %>

  <%= simple_form_for '', method: :get do |f| %>
    <%= f.input :studio_number, label: false, placeholder: "search by studio" %>
  <% end %>

</nav>

<% @users.each do |user| %>

  <p>
    <%= user.username %> (<%= user.email %>)
  </p>

<% end %>

app/views/users/new.html.erb
<% content_for :page_title, "Sign up" %>

<h2>Sign up</h2>

<%= simple_form_for @user do |f| %>

  <%= f.input :username %>
  <%= f.input :email %>
  <%= f.input :studio_number, label: "Studio number (optional)" %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>

  <%= f.button :submit, "Sign up" %>

<% end %>

app/views/users/show.html.erb
<% content_for :page_title, @user.username %>

<div class="profile-card">

  <div class="profile-info">
    <div class="user-list-item">
      <h2><%= @user.real_name %></h2>

      <% if @user.studio_number.present? and @user.real_name.present? %>
        <span>from studio <%= @user.studio_number %></span>
      <% end %>
    </div>

    <div class="more-info">
      <% if @user.description.present? %>
        <p class="label-info">About me:</p>
        <p class="description"><%= @user.description %></p>
      <% end %>

      <% if @user.birthday_date.present? %>
        <p class="label-info">My bday: <%= @user.birthday_date.strftime("%d %B, %Y") %></p>
      <% end %>
    </div>
  </div>

  <div class="wrapper-image profile-image">
    <% if @user.photo.medium.url.present? %>
      <%= image_tag @user.photo.medium.url %>
    <% end %>

    <% if @user.groups.any? %>

      <% @user.groups.each do |group| %>
        <p><%= link_to group.name, group_path(group) %></p>
      <% end %>

    <% end %>

  </div>

</div>

<div class="edit-profile-cta">
  <%= link_to "Edit profile", edit_user_path %>
</div>

<% if @user.receiver_testimonials.any? %>
  <h3>Testimonials</h3>

    <ul class="testimonials">
      <%= render partial: "testimonials/testimonial", collection:  @testimonials = Testimonial.where(:receiver_id => @user.id).includes(:author), as: :testimonial %>
    </ul>
<% end %>

<% if @user != @current_user %>
  <h3>Write a testimonial</h3>

  <%= simple_form_for [@user, Testimonial.new] do |f| %>

    <%= f.input :body, label: "Your testimonial" %>
    <%= f.button :submit, "Add testimonial" %>

  <% end %>
<% end %>