config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  # groups controller
  resources :groups

  # ads controller
  resources :ads do
    resources :comments
    resource :bookmark
  end

  # users could sign up multiple times
  resources :users do
    resources :testimonials
  end

  # users can only make one session
  resource :session

  resource :account

  get "about", to: "pages#about"
  
  root "pages#home"
end

app/models/ad.rb
class Ad < ApplicationRecord
  # add an association that has a 1-to-many relationship
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  # add an association to the user
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
  validates :category, presence: true

  def to_param
    id.to_s + '-' + title.parameterize
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :ad
  belongs_to :user

  validates :ad, uniqueness: { scope: :user }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :ad
  belongs_to :user

  validates :body, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users

  validates :name, presence: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/page.rb
class Page < ApplicationRecord
  validates :url, uniqueness: true

  mount_uploader :image, ContentImageUploader
end

app/models/testimonial.rb
class Testimonial < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :receiver, class_name: 'User'

  validates :body, presence: true
  validates :author_id, presence: true
  validates :receiver_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :ads, dependent: :destroy
  has_many :comments
  has_many :bookmarks, dependent: :destroy
  has_many :group_users
  has_many :groups, through: :group_users

  has_many :author_testimonials, class_name: 'Testimonial', foreign_key: 'author_id'
  has_many :receiver_testimonials, class_name: 'Testimonial', foreign_key: 'receiver_id'

  has_secure_password

  # add the photo uploader
  mount_uploader :photo, PhotoUploader

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true

  def to_param
    username
  end
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  def index
    @category = params[:category]

    @ads = if @category.present?
             # filter by category (request or offer)
             Ad.where(category: @category)
           else
             Ad.all
           end
  end

  def new
    @ad = Ad.new
  end

  def create
    @ad = Ad.new(form_params)

    # and then associate it with a user
    @ad.user = @current_user

    if @ad.save
      flash[:success] = 'Your ad was posted!'

      redirect_to root_path
    else
      # show the view for new.html.erb
      render 'new'
    end
  end

  def show
    @ad = Ad.find(params[:id])
  end

  def destroy
    @ad = Ad.find(params[:id])

    # destroy if they have access
    if @ad.user == @current_user
      @ad.destroy

      flash[:success] = 'Ad deleted successfully!'
    end

    # redirect to the home page
    redirect_to root_path
  end

  def edit
    @ad = Ad.find(params[:id])

    redirect_to root_path if @ad.user != @current_user
  end

  def update
    @ad = Ad.find(params[:id])

    if @ad.user != @current_user
      redirect_to root_path
    elsif @ad.update(form_params)
      flash[:success] = 'Ad updated successfully!'

      redirect_to ad_path(@ad)
    else
      render 'edit'
    end
  end

  def form_params
    params.require(:ad).permit(:title, :body, :category)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- website developed by Giamma using Ruby On Rails -->
<html>
  <head>
    <title><%= content_for :page_title %> | Uliving Rio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>
        <%= link_to root_path do %>
          <%= image_tag "logo-uliving.png" %>
        <% end %>
      </h1>

      <% if not is_logged_in? %>
        <h2>Bulletin Board</h2>
      <% end %>
      
      <nav class="navbar">
        <% if is_logged_in? %>

        <div class="username">
          <% if @current_user.username %>
            <%= link_to @current_user.username, user_path(@current_user) %>
          <% end %>
        </div>

        <div class="nav-actions logout">
          <% if @current_user.is_admin? %>
            <%= link_to "Admin", admin_root_path %>
          <% end %>

          <%= link_to "New ad", new_ad_path %>
          
          <%= link_to "Edit account", edit_account_path %>

          <%= link_to "Log out", session_path, method: :delete %>
        </div>

        <% else %>

        <div class="nav-actions login">
          <%= link_to "Sign up", new_user_path %>
          <%= link_to "Log in", new_session_path %>
        </div>

        <% end %>

      </nav>
    </header>

    <% if flash[:success].present? %>
      <div class="success">
        <%= flash[:success] %>
      </div>
    <% end %>

    <main>
      <%= yield %>
    </main>

    <footer>&copy; 2022 Uliving | <%= link_to "About", about_path %></footer>
  </body>
</html>

app/views/pages/_ad.html.erb
<li class="latest-ad-item">
  <%= link_to ad.title, ad_path(ad) %>
</li>

app/views/pages/about.html.erb
<% content_for :page_title, "About" %>

<div class="wrapper-image">
  <% if @content.image.present? %>
    <%= image_tag @content.image.url %>
  <% end %>
</div>

<h1><%= @content.title %></h1>

<%= simple_format @content.body %>

app/views/pages/home.html.erb
<% content_for :page_title, "Home" %>

<h1><%= @content.title %></h1>

<div class="wrapper-image home">
  <% if @content.image.present? %>
    <%= image_tag @content.image.url %>
  <% end %>
</div>

<h2>
  <%= simple_format @content.body %>
</h2>

<% if @featured_ads.any? %>
  <h3 class="featured">
    <%= "Featured ads" %>
  </h3>

  <ul class="featured">
    <%= render partial: "ad", collection: @featured_ads %>
  </ul>

<% end %>

<% if @latest_ads.any? %>
  <h3 class="latest">
    <%= "Latest ads from your community" %>
  </h3>

  <ul class="latest">
    <%= render partial: "ad", collection: @latest_ads %>
  </ul>
<% end %>

<p class="more-ads">
  <%= link_to ">> See all ads", ads_path %>
</p>